-- DBUPDATE-034-0.SQL
-- Extend the existing audit log table for government document management

-- Make old columns nullable to avoid constraint violations with new entity
ALTER TABLE T_AUDIT_LOG ALTER COLUMN LOG_IDENTITY_C SET NULL;
ALTER TABLE T_AUDIT_LOG ALTER COLUMN LOG_CLASSENTITY_C SET NULL;
ALTER TABLE T_AUDIT_LOG ALTER COLUMN LOG_TYPE_C SET NULL;
ALTER TABLE T_AUDIT_LOG ALTER COLUMN LOG_MESSAGE_C SET NULL;

-- Add new columns if they don't exist
ALTER TABLE T_AUDIT_LOG ADD COLUMN IF NOT EXISTS LOG_USERID_C VARCHAR(36);
ALTER TABLE T_AUDIT_LOG ADD COLUMN IF NOT EXISTS LOG_USERNAME_C VARCHAR(50);
ALTER TABLE T_AUDIT_LOG ADD COLUMN IF NOT EXISTS LOG_ACTION_C VARCHAR(50);
ALTER TABLE T_AUDIT_LOG ADD COLUMN IF NOT EXISTS LOG_TARGETID_C VARCHAR(36);
ALTER TABLE T_AUDIT_LOG ADD COLUMN IF NOT EXISTS LOG_DETAIL_C CLOB;
ALTER TABLE T_AUDIT_LOG ADD COLUMN IF NOT EXISTS LOG_CLIENTIP_C VARCHAR(50);

-- Create indexes (ignore if already exists)
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOG_USER ON T_AUDIT_LOG (LOG_USERID_C);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOG_ACTION ON T_AUDIT_LOG (LOG_ACTION_C);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOG_TARGET ON T_AUDIT_LOG (LOG_TARGETID_C);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOG_DATE ON T_AUDIT_LOG (LOG_CREATEDATE_D);

update T_CONFIG set CFG_VALUE_C = '34' where CFG_ID_C = 'DB_VERSION';
