-- DBUPDATE-032-0.SQL
-- Government document management system extensions

-- Department table
CREATE TABLE T_DEPARTMENT (DEP_ID_C VARCHAR(36) PRIMARY KEY, DEP_NAME_C VARCHAR(100) NOT NULL, DEP_IDPARENT_C VARCHAR(36), DEP_CODE_C VARCHAR(50), DEP_SORTORDER_N INT DEFAULT 0, DEP_CREATEDATE_D TIMESTAMP, DEP_DELETEDATE_D TIMESTAMP);

-- Position table
CREATE TABLE T_POSITION (POS_ID_C VARCHAR(36) PRIMARY KEY, POS_NAME_C VARCHAR(100) NOT NULL, POS_LEVEL_N INT DEFAULT 1, POS_IDDEPARTMENT_C VARCHAR(36), POS_CREATEDATE_D TIMESTAMP, POS_DELETEDATE_D TIMESTAMP);

-- User-Position association table
CREATE TABLE T_USER_POSITION (UPO_ID_C VARCHAR(36) PRIMARY KEY, UPO_IDUSER_C VARCHAR(36) NOT NULL, UPO_IDPOSITION_C VARCHAR(36) NOT NULL, UPO_ISPRIMARY_B BOOLEAN DEFAULT TRUE, UPO_CREATEDATE_D TIMESTAMP);

-- Document classification table
CREATE TABLE T_DOC_CLASSIFICATION (DCL_ID_C VARCHAR(36) PRIMARY KEY, DCL_NAME_C VARCHAR(50) NOT NULL, DCL_CODE_C VARCHAR(20), DCL_SORTORDER_N INT DEFAULT 0, DCL_CREATEDATE_D TIMESTAMP, DCL_DELETEDATE_D TIMESTAMP);

-- Document table extensions
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_IDCLASSIFICATION_C VARCHAR(36);
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_SECRECYLEVEL_C VARCHAR(20) DEFAULT 'INTERNAL';
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_URGENCY_C VARCHAR(20) DEFAULT 'NORMAL';
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_DOCNO_C VARCHAR(100);
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_FROMUNIT_C VARCHAR(200);
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_IDHANDLERDEPT_C VARCHAR(36);
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_IDHANDLERUSER_C VARCHAR(36);
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_DOCDATE_D TIMESTAMP;
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_RETENTION_C VARCHAR(20);
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_ARCHIVENO_C VARCHAR(100);
ALTER TABLE T_DOCUMENT ADD COLUMN DOC_STATUS_C VARCHAR(20) DEFAULT 'DRAFT';

-- Initialize default document classifications (one INSERT per line)
INSERT INTO T_DOC_CLASSIFICATION (DCL_ID_C, DCL_NAME_C, DCL_CODE_C, DCL_SORTORDER_N, DCL_CREATEDATE_D, DCL_DELETEDATE_D) VALUES ('cls-001', '收文', 'RECEIVE', 1, NOW(), NULL);
INSERT INTO T_DOC_CLASSIFICATION (DCL_ID_C, DCL_NAME_C, DCL_CODE_C, DCL_SORTORDER_N, DCL_CREATEDATE_D, DCL_DELETEDATE_D) VALUES ('cls-002', '发文', 'SEND', 2, NOW(), NULL);
INSERT INTO T_DOC_CLASSIFICATION (DCL_ID_C, DCL_NAME_C, DCL_CODE_C, DCL_SORTORDER_N, DCL_CREATEDATE_D, DCL_DELETEDATE_D) VALUES ('cls-003', '会议纪要', 'MINUTES', 3, NOW(), NULL);
INSERT INTO T_DOC_CLASSIFICATION (DCL_ID_C, DCL_NAME_C, DCL_CODE_C, DCL_SORTORDER_N, DCL_CREATEDATE_D, DCL_DELETEDATE_D) VALUES ('cls-004', '通知公告', 'NOTICE', 4, NOW(), NULL);
INSERT INTO T_DOC_CLASSIFICATION (DCL_ID_C, DCL_NAME_C, DCL_CODE_C, DCL_SORTORDER_N, DCL_CREATEDATE_D, DCL_DELETEDATE_D) VALUES ('cls-005', '工作报告', 'REPORT', 5, NOW(), NULL);
INSERT INTO T_DOC_CLASSIFICATION (DCL_ID_C, DCL_NAME_C, DCL_CODE_C, DCL_SORTORDER_N, DCL_CREATEDATE_D, DCL_DELETEDATE_D) VALUES ('cls-006', '请示报告', 'REQUEST', 6, NOW(), NULL);

-- Update the database version
update T_CONFIG set CFG_VALUE_C = '32' where CFG_ID_C = 'DB_VERSION';
