-- DBUPDATE-033-0.SQL
-- 3D role-based access control extensions

-- Add role fields to user table
ALTER TABLE T_USER ADD COLUMN USE_ADMINTYPE_C VARCHAR(20) DEFAULT 'NON_ADMIN';
ALTER TABLE T_USER ADD COLUMN USE_SECRECYLEVEL_C VARCHAR(20) DEFAULT 'UNCLASSIFIED';
ALTER TABLE T_USER ADD COLUMN USE_CLASSIFIER_B BOOLEAN DEFAULT FALSE;

-- Set admin user as system administrator with core classified clearance
UPDATE T_USER SET USE_ADMINTYPE_C = 'SYSTEM_ADMIN', USE_SECRECYLEVEL_C = 'CORE_CLASSIFIED', USE_CLASSIFIER_B = TRUE WHERE USE_USERNAME_C = 'admin';

-- Update the database version
update T_CONFIG set CFG_VALUE_C = '33' where CFG_ID_C = 'DB_VERSION';
